CREATE TABLE users (id INT AUTO_INCREMENT NOT NULL, profile INT DEFAULT NULL, friend INT DEFAULT NULL, address INT DEFAULT NULL, name VARCHAR(255) NOT NULL, password VARCHAR(255) NOT NULL, email VARCHAR(255) NOT NULL, avatar VARCHAR(255) DEFAULT '', birthDate DATETIME NOT NULL, UNIQUE INDEX UNIQ_1483A5E9E7927C74 (email), INDEX name_email_index (name, email), INDEX IDX_1483A5E98157AA0F (profile), INDEX IDX_1483A5E955EEAC61 (friend), INDEX IDX_1483A5E9D4E6F81 (address), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB
CREATE TABLE profile (id INT AUTO_INCREMENT NOT NULL, address INT DEFAULT NULL, user INT DEFAULT NULL, age INT NOT NULL, tags LONGTEXT NOT NULL COMMENT '(DC2Type:simple_array)', INDEX IDX_8157AA0FD4E6F81 (address), INDEX IDX_8157AA0F8D93D649 (user), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB
CREATE TABLE address (id INT AUTO_INCREMENT NOT NULL, city INT DEFAULT NULL, INDEX IDX_D4E6F812D5B0234 (city), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB
CREATE TABLE city (id INT AUTO_INCREMENT NOT NULL, name VARCHAR(255) NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB
ALTER TABLE users ADD CONSTRAINT FK_1483A5E98157AA0F FOREIGN KEY (profile) REFERENCES profile (id) ON UPDATE CASCADE
ALTER TABLE users ADD CONSTRAINT FK_1483A5E955EEAC61 FOREIGN KEY (friend) REFERENCES users (id) ON UPDATE CASCADE
ALTER TABLE users ADD CONSTRAINT FK_1483A5E9D4E6F81 FOREIGN KEY (address) REFERENCES address (id) ON UPDATE CASCADE
ALTER TABLE profile ADD CONSTRAINT FK_8157AA0FD4E6F81 FOREIGN KEY (address) REFERENCES address (id) ON UPDATE CASCADE
ALTER TABLE profile ADD CONSTRAINT FK_8157AA0F8D93D649 FOREIGN KEY (user) REFERENCES users (id) ON UPDATE CASCADE
ALTER TABLE address ADD CONSTRAINT FK_D4E6F812D5B0234 FOREIGN KEY (city) REFERENCES city (id) ON UPDATE CASCADE
